### ISSUE TITLE
Trotz Eur nur als USD

### ISSUE THREAD

**Issue by guergen1** [waoler/iobroker.stockmarket#10]
Ich habe mehrere EUR-Aktien und Fonds korrekt eingetreagen, die Datenpunkte werden auch entsprechend erstellt. Jedoch wird als Einheit immer USD eingetragen, obwohl es sich um EURo handelt

**Comment by waoler** [comment]
Der Adapter schreibt bei jeder Aktie USD dahinter, unabhängig von der eigentlichen Währung. Bis jetzt dachte ich auch, dass alle Aktien bei Alphavantage in US Dollar angegeben werden.

**Comment by guergen1** [comment]
Habe als erste Hilfe jetzt die DP in EUR geändert, wäre vielleicht schön, wenn direkt der richtige Wert eingetragen würde
