### ISSUE TITLE
Adapter already running -Fehler

### ISSUE THREAD

**Issue by guergen1** [waoler/iobroker.stockmarket#11]
lt. changelog soll der Fehler weg sein in der Version 0.0.2
Bei mir jedoch kommt die folgende Fehlermeldung:
`

host.iobroker | 2020-03-31 11:30:00.004 | warn | instance system.adapter.stockmarket.0 already running with pid 6337
-- | -- | -- | --

`
Updates gibt es auch keine der eingetragenen Aktien

**Comment by Knacki** [comment]
hier ist leider das selbe Problem... Wahrscheinlich beendet sich der Adapter nicht korrekt. 
Durch den CronJob wird er dann zwar wieder gestartet aber als neuer Prozess... Daher kommt leider auch die Fehlermeldung.. Abhilfe ist nur den Prozess mit sudo kill "pidnummer" zu beenden.
Dann startet stockmaket wieder korrekt und holt auch Daten ab, jedoch kommt dann wieder das ursprüngliche Problem das er sich nicht korrekt beendet.
Vielleicht kann der Entwickler hier noch mal prüfen woran das liegt...

**Comment by ma-gu-16** [comment]
gleiches problem bei mir. 

habe 3 instanzen angelegt um das 5 request limit zu umgehen. cronjob jeweils um 2 minuten versetzt.

**Comment by thost96** [comment]
duplicate of #3
