### ISSUE TITLE
CRON läuft nicht

### ISSUE THREAD

**Issue by m-s-b** [waoler/ioBroker.stockmarket#2]
Sobald die Instanz das erste Mal gestartet wird ruft er die Kurse ab.
Standardmäßig sollte er dann alle 15 min die Kurse neu abrufen.
Im Log erscheint dann die Meldung
`instance system.adapter.stockmarket.0 already running with pid 22980`
Wenn ich den Prozess über die Konsole kille, oder das System neu starte ruft er einmalig wieder die Kurse ab.

**Comment by waoler** [comment]
Sollte jetzt gefixed sein. Lösch am besten einmal den ganzen Adapter und installier ihn neu.
Meld dich nochmal wenn es geklappt hat, oder auch nicht :)

**Comment by m-s-b** [comment]
Also er ruft die Aktien jetzt im Intervall ab. Irgendwas läuft aber noch nicht ganz rund, oder ich verstehe das Log nicht ;-)
`
stockmarket.0 | 2019-11-19 14:15:03.461 | info | (15414) checking stock for: OSR.DEX with URL: https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=OSR.DEX&interval=5min&apikey=XXX
-- | -- | -- | --
stockmarket.0 | 2019-11-19 14:15:03.368 | info | (15414) checking stock for: SIE.DEX with URL: https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=SIE.DEX&interval=5min&apikey=XXX
stockmarket.0 | 2019-11-19 14:15:03.366 | info | (15414) stocks to check: SIE.DEX,OSR.DEX
stockmarket.0 | 2019-11-19 14:15:03.364 | info | (15414) APIKEY is set: 'XXX'
stockmarket.0 | 2019-11-19 14:15:03.362 | info | (15414) initialize stock market adapter
stockmarket.0 | 2019-11-19 14:15:03.295 | info | (15414) starting. Version 0.0.2 in /opt/iobroker/node_modules/iobroker.stockmarket, node: v10.17.0
host.rock64 | 2019-11-19 14:15:00.626 | error | instance system.adapter.stockmarket.0 terminated with code 156 (156)
stockmarket.0 | 2019-11-19 14:15:00.090 | info | (11856) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
stockmarket.0 | 2019-11-19 14:15:00.088 | info | (11856) terminating
stockmarket.0 | 2019-11-19 14:15:00.083 | info | (11856) cleaned everything up...
stockmarket.0 | 2019-11-19 14:15:00.079 | warn | (11856) Got terminate signal. Checking desired PID: 0 vs own PID 11856
host.rock64 | 2019-11-19 14:15:00.069 | info | instance system.adapter.stockmarket.0 started with pid 15414

`

**Comment by waoler** [comment]
Doch, das sieht wunderbar aus. Genau so soll das aussehen :)

Ich bearbeite die Konsolenausgabe noch im nächsten Update, sodass dort nicht mehr so viel angezeigt wird. Ist tatsächlich ein bisschen verwirrend.
Danke für deine Hilfe, ich schließe hier dann.

**Comment by m-s-b** [comment]
Also so richtig rund läuft das (bei mir) noch nicht.... Gestern Abend hat sich das dann wieder aufgehangen
`instance system.adapter.stockmarket.0 already running with pid 22980`
Nach einem kill 22980 hat es wieder einmal funktioniert und dann wieder der Fehler...
Lass jetzt mal testweise den Adapter via Cron regelmäßig neustarten. Hin und wieder kommt der Fehler zwar noch, aber meistens klappt es.

**Comment by ma-gu-16** [comment]
dieses Problem besteht noch immer.

**Comment by Ajimaru** [comment]
Habe es aufgegeben und den Adapter deinstalliert.
