### ISSUE TITLE
mehrere Aktiennummern angegeben aber nur ein Kurs in den Objekten

### ISSUE THREAD

**Issue by Ajimaru** [waoler/iobroker.stockmarket#5]
In der Adapterkonfiguration habe ich mehrere Aktiennummern Kommagetrennt angegeben.
Es wird abere nur eine Aktie in die Objekte geschrieben.
![Aktiennummern](https://user-images.githubusercontent.com/38381946/73474487-d8352500-438e-11ea-8f67-8dd094cc3005.PNG)
![Objekte](https://user-images.githubusercontent.com/38381946/73474503-e08d6000-438e-11ea-9673-9a38fff1ab88.PNG)

**Comment by waoler** [comment]
Ich kann das Problem leider nicht reproduzieren.

![grafik](https://user-images.githubusercontent.com/5882862/77835672-54f63c80-714f-11ea-8203-f807ddecb0ee.png)

![grafik](https://user-images.githubusercontent.com/5882862/77835681-68a1a300-714f-11ea-9527-117b1cd1901f.png)

Vielleicht liegt es an der Beschränkung von Alphavantage, dass nur 5 Abfragen pro Minute durchgeführt werden dürfen. Allerdings hast du auf deinem Screenshot nur 5 Aktien, womit das eigentlich noch korrekt ausgeführt werden dürfte.
